
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true

analyzer:
  errors:
    invalid_annotation_target: false
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
