name: polypass
description: A password manager written in Dart/Flutter

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-0"

dependencies:
  bloc: ^8.0.3
  encrypt: ^5.0.1
  equatable: ^2.0.3
  ffi: ^2.0.1
  file_picker: 5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_rust_bridge: ^1.61.1
  freezed_annotation: ^2.0.3
  ftpconnect: ^2.0.2
  go_router: ^6.0.1
  hash: ^1.0.4
  json_annotation: ^4.5.0
  path_provider: ^2.0.11
  pointycastle: ^3.6.1
  provider: ^6.0.3
  sizer: ^2.0.15
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  ffigen: ^7.2.4

flutter:
  uses-material-design: true
  assets:
    - assets/polypass.png
